"""Add cover_url to Record model

Revision ID: 17e56194b7c3
Revises: 2e2300741627
Create Date: 2025-04-25 00:37:47.742128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e56194b7c3'
down_revision = '2e2300741627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'cover_url')
    # ### end Alembic commands ### 