"""Add rating table

Revision ID: 2e2300741627
Revises: 0f9c497c0041
Create Date: 2025-04-23 22:29:34.183130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2300741627'
down_revision: Union[str, None] = '0f9c497c0041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ensure the table doesn't exist before creating (robustness for retries)
    op.drop_table('ratings', if_exists=True)
    
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    
    with op.batch_alter_table('selections', schema=None) as batch_op:
        batch_op.alter_column('participants',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        batch_op.alter_column('weight_changes',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selections', schema=None) as batch_op:
        batch_op.alter_column('weight_changes',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('participants',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
                   
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ### 