"""Add rym_url to Record model

Revision ID: b568b0ac4f07
Revises: 17e56194b7c3
Create Date: 2025-04-25 01:21:14.399806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b568b0ac4f07'
down_revision = '17e56194b7c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('rym_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'rym_url')
    # ### end Alembic commands ### 