"""Update record ownership model

Revision ID: c37436c6b6a3
Revises: fe1d983e09b1
Create Date: 2025-04-01 22:02:59.174439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37436c6b6a3'
down_revision = 'fe1d983e09b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'users', ['owner_id'], ['id'])
    op.drop_column('records', 'person_id')
    op.add_column('selections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'selections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selections', type_='foreignkey')
    op.drop_column('selections', 'user_id')
    op.add_column('records', sa.Column('person_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'persons', ['person_id'], ['id'])
    op.drop_column('records', 'owner_id')
    # ### end Alembic commands ### 