"""Initial migration

Revision ID: fe1d983e09b1
Revises: 11ac284dafac
Create Date: 2025-04-01 20:22:32.202779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1d983e09b1'
down_revision = '11ac284dafac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 